### ISSUE TITLE
$ref'd schemas are not moved to temp folder, causing exceptions

### ISSUE THREAD

**Issue by jayashe** [mulesoft-labs/raml-jaxrs-codegen#19]
Working with raml-jaxrs-codegen-core (within a larger code-generation project)

I have a schemas section that looks like this:

```
schemas:
    - schema-1.json: !include ./schema/schema-1.json
    - schema-2.json: !include ./schema/schema-2.json
    - schema-3.json: !include ./schema/schema-3.json
```

Some of those schemas reference other JSON files that are in the ./schemas folder. 

getConsolidatedSchemas() from raml-java-parser only returns the three highest-level schemas, and not any that are referenced within. This means that only those three files are created or copied to the temp folder, and the referenced ones are omitted, resulting in a file  not found exception. 

Is this an issue with raml-jaxrs-codegen or raml-java-parser?
